AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Autonomous AI Research Agent Root Template

Resources:
  DataStack:
    Type: AWS::Serverless::Application
    Properties:
      Location: stacks/data.yaml

  ApiStack:
    Type: AWS::Serverless::Application
    Properties:
      Location: stacks/api.yaml

  AgentStack:
    Type: AWS::Serverless::Application
    Properties:
      Location: stacks/agent.yaml

  MemoryStack:
    Type: AWS::Serverless::Application
    Properties:
      Location: stacks/memory.yaml

